const OG_IMAGE = "https://www.khadijaexim.com/og-image.jpg";

export function buildSeoMetadata(seo) {
  return {
    title: seo.title,
    description: seo.description,
    keywords: seo.keywords,
    alternates: {
      canonical: seo.canonical,
    },
    openGraph: {
      title: seo.ogTitle,
      description: seo.ogDescription,
      url: seo.canonical,
      type: "website",
      images: [OG_IMAGE],
    },
  };
}

export const pageSeo = {
  home: {
    title: "Dehydrated Food Products Exporter India | Khadija Exim",
    description: "Khadija Exim exports premium dehydrated onion, garlic & vegetables from Gujarat, India. Bulk supply for food manufacturers & importers worldwide. Request quote.",
    canonical: "https://www.khadijaexim.com/",
    ogTitle: "Dehydrated Food Products Exporter from India | Khadija Exim",
    ogDescription: "Premium dehydrated onion, garlic & vegetables from Gujarat. Bulk B2B supply for importers & food manufacturers worldwide.",
    keywords: "dehydrated food products exporter India, dehydrated onion exporter Gujarat, garlic powder bulk supplier India, dehydrated vegetables exporter",
  },
  about: {
    title: "About Khadija Exim | Dehydrated Food Exporter Gujarat India",
    description: "Khadija Exim is a trusted dehydrated food products exporter from Wankaner, Gujarat. Premium onion & garlic supply to global importers & food manufacturers.",
    canonical: "https://www.khadijaexim.com/about",
    ogTitle: "About Khadija Exim | Dehydrated Food Products Exporter India",
    ogDescription: "Based in Gujarat, India's leading agri-export hub. Supplying premium dehydrated onion & garlic to importers and food manufacturers worldwide.",
    keywords: "Khadija Exim about, dehydrated vegetable exporter Wankaner, Gujarat food exporter, dehydrated onion garlic supplier India",
  },
  products: {
    title: "Dehydrated Onion & Garlic Products | Khadija Exim India",
    description: "Browse Khadija Exim's full range — dehydrated white, red & pink onion plus garlic in flakes, powder, granules, minced & chopped. Bulk B2B export from India.",
    canonical: "https://www.khadijaexim.com/products",
    ogTitle: "Dehydrated Onion & Garlic Products | Khadija Exim",
    ogDescription: "Complete range of dehydrated onion & garlic products for bulk export. White, Red, Pink Onion & Garlic — flakes, powder, granules & more.",
    keywords: "dehydrated onion products India, dehydrated garlic products Gujarat, bulk onion powder export, onion flakes garlic flakes supplier",
  },
  industries: {
    title: "Industries We Serve | Khadija Exim Dehydrated Products",
    description: "Khadija Exim supplies dehydrated onion & garlic to food processing, seasoning, snacks, instant foods, HoReCa, sauces & importers worldwide. Bulk B2B export.",
    canonical: "https://www.khadijaexim.com/industries",
    ogTitle: "Industries Served | Khadija Exim — Dehydrated Food Exporter India",
    ogDescription: "Supplying dehydrated vegetables to food processors, seasoning manufacturers, snack producers, instant food brands & global importers.",
    keywords: "dehydrated onion garlic food processing industry, seasoning manufacturer supplier India, snack industry dehydrated vegetable supplier",
  },
  contact: {
    title: "Contact Khadija Exim | Bulk Dehydrated Export Inquiry",
    description: "Contact Khadija Exim for bulk dehydrated onion & garlic export inquiries. Based in Wankaner, Gujarat, India. Fast response. Send your requirements today.",
    canonical: "https://www.khadijaexim.com/contact",
    ogTitle: "Contact Khadija Exim | Dehydrated Food Export Inquiry",
    ogDescription: "Reach out to Khadija Exim for bulk dehydrated onion & garlic export. Wankaner, Gujarat, India. Quick response guaranteed.",
    keywords: "contact dehydrated vegetable exporter India, bulk onion garlic export inquiry, Khadija Exim contact Gujarat",
  },
};

export const productCategorySeo = {
  white: {
    title: "Dehydrated White Onion Exporter India | Bulk Supplier",
    description: "Buy dehydrated white onion flakes, powder, granules, minced & chopped from Gujarat, India. A-grade quality, bulk supply for importers & food manufacturers.",
    canonical: "https://www.khadijaexim.com/products?category=white",
    ogTitle: "Dehydrated White Onion Exporter India | Khadija Exim",
    ogDescription: "Premium dehydrated white onion — flakes, powder, granules, minced, chopped. Bulk export from Gujarat, India.",
    keywords: "dehydrated white onion exporter India, white onion flakes bulk supplier, white onion powder export Gujarat",
  },
  red: {
    title: "Dehydrated Red Onion Exporter India | Bulk Supplier",
    description: "Premium dehydrated red onion flakes, powder, granules, minced & chopped from Gujarat, India. Bulk B2B export supply worldwide.",
    canonical: "https://www.khadijaexim.com/products?category=red",
    ogTitle: "Dehydrated Red Onion Exporter India | Khadija Exim",
    ogDescription: "Export-grade dehydrated red onion — flakes, powder, granules. Bulk supply from Gujarat, India.",
    keywords: "dehydrated red onion exporter India, red onion flakes supplier Gujarat, red onion powder bulk export",
  },
  pink: {
    title: "Dehydrated Pink Onion Exporter India | Bulk Supplier",
    description: "Export-grade dehydrated pink onion flakes, powder, granules, minced & chopped. Bulk supply from Gujarat, India to global importers.",
    canonical: "https://www.khadijaexim.com/products?category=pink",
    ogTitle: "Dehydrated Pink Onion Exporter India | Khadija Exim",
    ogDescription: "Premium dehydrated pink onion in flakes, powder & granules. Bulk export from Gujarat, India.",
    keywords: "dehydrated pink onion exporter India, pink onion flakes supplier, pink onion powder bulk Gujarat",
  },
  garlic: {
    title: "Dehydrated Garlic Exporter India | Bulk Supplier Gujarat",
    description: "Buy dehydrated garlic flakes, powder, granules, minced & chopped from Gujarat, India. High allicin content. Bulk B2B export supply worldwide.",
    canonical: "https://www.khadijaexim.com/products?category=garlic",
    ogTitle: "Dehydrated Garlic Exporter India | Khadija Exim Gujarat",
    ogDescription: "Premium dehydrated garlic — flakes, powder, granules, minced, chopped. Bulk export from Gujarat, India.",
    keywords: "dehydrated garlic exporter India, garlic powder bulk supplier Gujarat, garlic flakes exporter India",
  },
};

export const productSeo = {
  "white-onion-flakes": {
    title: "White Onion Flakes Exporter India | Khadija Exim",
    description: "Buy dehydrated white onion flakes from Gujarat, India. 8–20mm kibbled, moisture max 6%, A-grade. Bulk supply for food manufacturers & importers.",
    canonical: "https://www.khadijaexim.com/products/white-onion-flakes",
    ogTitle: "White Onion Flakes Exporter India | Khadija Exim",
    ogDescription: "Buy dehydrated white onion flakes from Gujarat, India. 8–20mm kibbled, moisture max 6%, A-grade. Bulk supply for food manufacturers & importers.",
    keywords: "white onion flakes exporter India, dehydrated white onion kibbled supplier, bulk onion flakes Gujarat",
  },
  "white-onion-powder": {
    title: "White Onion Powder Exporter India | Bulk Supplier",
    description: "Premium dehydrated white onion powder 80–100 mesh from Gujarat, India. Moisture max 6%. Bulk B2B supply for seasoning & food manufacturers.",
    canonical: "https://www.khadijaexim.com/products/white-onion-powder",
    ogTitle: "White Onion Powder Exporter India | Bulk Supplier",
    ogDescription: "Premium dehydrated white onion powder 80–100 mesh from Gujarat, India. Moisture max 6%. Bulk B2B supply for seasoning & food manufacturers.",
    keywords: "white onion powder exporter India, dehydrated onion powder bulk supplier, onion powder Gujarat export",
  },
  "white-onion-granules": {
    title: "White Onion Granules Exporter India | Khadija Exim",
    description: "Export-grade dehydrated white onion granules from Gujarat, India. 0.5–1mm size, moisture max 6%. Bulk supply for global importers.",
    canonical: "https://www.khadijaexim.com/products/white-onion-granules",
    ogTitle: "White Onion Granules Exporter India | Khadija Exim",
    ogDescription: "Export-grade dehydrated white onion granules from Gujarat, India. 0.5–1mm size, moisture max 6%. Bulk supply for global importers.",
    keywords: "white onion granules exporter India, dehydrated onion granules supplier Gujarat, onion granules bulk export",
  },
  "white-onion-minced": {
    title: "Dehydrated White Onion Minced Exporter India",
    description: "Premium dehydrated white onion minced 1–3mm from Gujarat, India. A-grade quality, moisture max 6%. Bulk export for food manufacturers worldwide.",
    canonical: "https://www.khadijaexim.com/products/white-onion-minced",
    ogTitle: "Dehydrated White Onion Minced Exporter India",
    ogDescription: "Premium dehydrated white onion minced 1–3mm from Gujarat, India. A-grade quality, moisture max 6%. Bulk export for food manufacturers worldwide.",
    keywords: "dehydrated white onion minced exporter India, onion minced bulk supplier Gujarat, white onion minced export",
  },
  "white-onion-chopped": {
    title: "Dehydrated White Onion Chopped Exporter India",
    description: "Buy dehydrated white onion chopped 3–5mm from Gujarat, India. Moisture max 6%, A-grade. Bulk B2B supply for importers & food manufacturers.",
    canonical: "https://www.khadijaexim.com/products/white-onion-chopped",
    ogTitle: "Dehydrated White Onion Chopped Exporter India",
    ogDescription: "Buy dehydrated white onion chopped 3–5mm from Gujarat, India. Moisture max 6%, A-grade. Bulk B2B supply for importers & food manufacturers.",
    keywords: "dehydrated white onion chopped supplier India, onion chopped bulk exporter Gujarat, white onion chopped export",
  },
  "red-onion-flakes": {
    title: "Red Onion Flakes Exporter India | Khadija Exim",
    description: "Premium dehydrated red onion flakes kibbled from Gujarat, India. 8–20mm, moisture max 6%. Bulk export supply for global food manufacturers.",
    canonical: "https://www.khadijaexim.com/products/red-onion-flakes",
    ogTitle: "Red Onion Flakes Exporter India | Khadija Exim",
    ogDescription: "Premium dehydrated red onion flakes kibbled from Gujarat, India. 8–20mm, moisture max 6%. Bulk export supply for global food manufacturers.",
    keywords: "red onion flakes exporter India, dehydrated red onion kibbled supplier, red onion flakes bulk Gujarat",
  },
  "red-onion-powder": {
    title: "Red Onion Powder Exporter India | Bulk Supplier",
    description: "Export-grade dehydrated red onion powder 80–100 mesh from Gujarat. Moisture max 6%. Bulk supply for seasoning manufacturers & importers.",
    canonical: "https://www.khadijaexim.com/products/red-onion-powder",
    ogTitle: "Red Onion Powder Exporter India | Bulk Supplier",
    ogDescription: "Export-grade dehydrated red onion powder 80–100 mesh from Gujarat. Moisture max 6%. Bulk supply for seasoning manufacturers & importers.",
    keywords: "red onion powder exporter India, dehydrated red onion powder bulk supplier Gujarat",
  },
  "red-onion-granules": {
    title: "Red Onion Granules Exporter India | Khadija Exim",
    description: "Dehydrated red onion granules 0.5–1mm from Gujarat, India. A-grade, moisture max 6%. Bulk B2B export for food manufacturers worldwide.",
    canonical: "https://www.khadijaexim.com/products/red-onion-granules",
    ogTitle: "Red Onion Granules Exporter India | Khadija Exim",
    ogDescription: "Dehydrated red onion granules 0.5–1mm from Gujarat, India. A-grade, moisture max 6%. Bulk B2B export for food manufacturers worldwide.",
    keywords: "red onion granules exporter India, dehydrated red onion granules supplier Gujarat",
  },
  "red-onion-minced": {
    title: "Dehydrated Red Onion Minced Exporter India",
    description: "Premium dehydrated red onion minced 1–3mm from Gujarat, India. Bulk supply, moisture max 6%. For food processors & global importers.",
    canonical: "https://www.khadijaexim.com/products/red-onion-minced",
    ogTitle: "Dehydrated Red Onion Minced Exporter India",
    ogDescription: "Premium dehydrated red onion minced 1–3mm from Gujarat, India. Bulk supply, moisture max 6%. For food processors & global importers.",
    keywords: "red onion minced exporter India, dehydrated red onion minced supplier Gujarat, bulk onion minced export",
  },
  "red-onion-chopped": {
    title: "Dehydrated Red Onion Chopped Exporter India",
    description: "Export-grade dehydrated red onion chopped 3–5mm from Gujarat. Moisture max 6%, A-grade. Bulk B2B supply for importers & manufacturers.",
    canonical: "https://www.khadijaexim.com/products/red-onion-chopped",
    ogTitle: "Dehydrated Red Onion Chopped Exporter India",
    ogDescription: "Export-grade dehydrated red onion chopped 3–5mm from Gujarat. Moisture max 6%, A-grade. Bulk B2B supply for importers & manufacturers.",
    keywords: "red onion chopped exporter India, dehydrated red onion chopped supplier Gujarat",
  },
  "pink-onion-flakes": {
    title: "Pink Onion Flakes Exporter India | Khadija Exim",
    description: "Premium dehydrated pink onion flakes kibbled 8–20mm from Gujarat, India. Moisture max 6%. Bulk supply for food manufacturers & importers.",
    canonical: "https://www.khadijaexim.com/products/pink-onion-flakes",
    ogTitle: "Pink Onion Flakes Exporter India | Khadija Exim",
    ogDescription: "Premium dehydrated pink onion flakes kibbled 8–20mm from Gujarat, India. Moisture max 6%. Bulk supply for food manufacturers & importers.",
    keywords: "pink onion flakes exporter India, dehydrated pink onion kibbled supplier Gujarat",
  },
  "pink-onion-powder": {
    title: "Pink Onion Powder Exporter India | Bulk Supplier",
    description: "Dehydrated pink onion powder 80–100 mesh from Gujarat, India. A-grade quality, bulk B2B export for seasoning & food manufacturers.",
    canonical: "https://www.khadijaexim.com/products/pink-onion-powder",
    ogTitle: "Pink Onion Powder Exporter India | Bulk Supplier",
    ogDescription: "Dehydrated pink onion powder 80–100 mesh from Gujarat, India. A-grade quality, bulk B2B export for seasoning & food manufacturers.",
    keywords: "pink onion powder exporter India, dehydrated pink onion powder bulk supplier Gujarat",
  },
  "pink-onion-granules": {
    title: "Pink Onion Granules Exporter India | Khadija Exim",
    description: "Export-grade dehydrated pink onion granules 0.5–1mm from Gujarat. Moisture max 6%. Bulk supply for global importers & food manufacturers.",
    canonical: "https://www.khadijaexim.com/products/pink-onion-granules",
    ogTitle: "Pink Onion Granules Exporter India | Khadija Exim",
    ogDescription: "Export-grade dehydrated pink onion granules 0.5–1mm from Gujarat. Moisture max 6%. Bulk supply for global importers & food manufacturers.",
    keywords: "pink onion granules exporter India, dehydrated pink onion granules supplier Gujarat",
  },
  "pink-onion-minced": {
    title: "Dehydrated Pink Onion Minced Exporter India",
    description: "Premium dehydrated pink onion minced 1–3mm from Gujarat, India. Bulk supply, moisture max 6%, A-grade for food processors worldwide.",
    canonical: "https://www.khadijaexim.com/products/pink-onion-minced",
    ogTitle: "Dehydrated Pink Onion Minced Exporter India",
    ogDescription: "Premium dehydrated pink onion minced 1–3mm from Gujarat, India. Bulk supply, moisture max 6%, A-grade for food processors worldwide.",
    keywords: "pink onion minced exporter India, dehydrated pink onion minced supplier Gujarat",
  },
  "pink-onion-chopped": {
    title: "Dehydrated Pink Onion Chopped Exporter India",
    description: "Buy dehydrated pink onion chopped 3–5mm from Gujarat, India. Moisture max 6%. Bulk B2B export for importers & food manufacturers.",
    canonical: "https://www.khadijaexim.com/products/pink-onion-chopped",
    ogTitle: "Dehydrated Pink Onion Chopped Exporter India",
    ogDescription: "Buy dehydrated pink onion chopped 3–5mm from Gujarat, India. Moisture max 6%. Bulk B2B export for importers & food manufacturers.",
    keywords: "pink onion chopped exporter India, dehydrated pink onion chopped supplier Gujarat",
  },
  "garlic-flakes": {
    title: "Garlic Flakes Exporter India | Bulk Supplier Gujarat",
    description: "Premium dehydrated garlic flakes 8–15mm from Gujarat, India. Moisture max 4%, high allicin. Bulk export for food manufacturers worldwide.",
    canonical: "https://www.khadijaexim.com/products/garlic-flakes",
    ogTitle: "Garlic Flakes Exporter India | Bulk Supplier Gujarat",
    ogDescription: "Premium dehydrated garlic flakes 8–15mm from Gujarat, India. Moisture max 4%, high allicin. Bulk export for food manufacturers worldwide.",
    keywords: "garlic flakes exporter India, dehydrated garlic flakes bulk supplier Gujarat, garlic flakes kibbled export",
  },
  "garlic-powder": {
    title: "Garlic Powder Exporter India | Bulk Supplier Gujarat",
    description: "Buy dehydrated garlic powder 80–100 mesh from Gujarat, India. Moisture max 6%, high purity. Bulk B2B supply for seasoning & food manufacturers.",
    canonical: "https://www.khadijaexim.com/products/garlic-powder",
    ogTitle: "Garlic Powder Exporter India | Bulk Supplier Gujarat",
    ogDescription: "Buy dehydrated garlic powder 80–100 mesh from Gujarat, India. Moisture max 6%, high purity. Bulk B2B supply for seasoning & food manufacturers.",
    keywords: "garlic powder exporter India, dehydrated garlic powder bulk supplier Gujarat, garlic powder export India",
  },
  "garlic-granules": {
    title: "Garlic Granules Exporter India | Khadija Exim",
    description: "Export-grade dehydrated garlic granules 0.5–1mm from Gujarat, India. Moisture max 6%. Bulk supply for global importers & food manufacturers.",
    canonical: "https://www.khadijaexim.com/products/garlic-granules",
    ogTitle: "Garlic Granules Exporter India | Khadija Exim",
    ogDescription: "Export-grade dehydrated garlic granules 0.5–1mm from Gujarat, India. Moisture max 6%. Bulk supply for global importers & food manufacturers.",
    keywords: "garlic granules exporter India, dehydrated garlic granules bulk supplier Gujarat",
  },
  "garlic-minced": {
    title: "Dehydrated Garlic Minced Exporter India | Khadija Exim",
    description: "Premium dehydrated garlic minced 1–3mm from Gujarat, India. Moisture max 6%, A-grade. Bulk export for food processors & importers worldwide.",
    canonical: "https://www.khadijaexim.com/products/garlic-minced",
    ogTitle: "Dehydrated Garlic Minced Exporter India | Khadija Exim",
    ogDescription: "Premium dehydrated garlic minced 1–3mm from Gujarat, India. Moisture max 6%, A-grade. Bulk export for food processors & importers worldwide.",
    keywords: "garlic minced exporter India, dehydrated garlic minced supplier Gujarat, bulk garlic minced export",
  },
  "garlic-chopped": {
    title: "Dehydrated Garlic Chopped Exporter India | Khadija Exim",
    description: "Buy dehydrated garlic chopped 3–5mm from Gujarat, India. Moisture max 6%, high purity. Bulk B2B export supply for importers worldwide.",
    canonical: "https://www.khadijaexim.com/products/garlic-chopped",
    ogTitle: "Dehydrated Garlic Chopped Exporter India | Khadija Exim",
    ogDescription: "Buy dehydrated garlic chopped 3–5mm from Gujarat, India. Moisture max 6%, high purity. Bulk B2B export supply for importers worldwide.",
    keywords: "garlic chopped exporter India, dehydrated garlic chopped supplier Gujarat, bulk garlic chopped export",
  },
};
